spring:
  application:
    name: notification-service
  profiles:
    active: local

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://smartorder:smartorder123@mongodb:27017/notification_db}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:supersecret_rmq_password}

server:
  port: 8082
  servlet:
    context-path: /api/v1

management:
  server:
    port: 8092
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
